name: "auto-version"
description: "Update package.json version"

inputs:
  major:
    description: "Commit message prefixes to trigger an update of the major version number"
    required: false
    default: "[MAJOR]"

  minor:
    description: "Commit message prefixes to trigger an update of the minor version number"
    required: false
    default: "[MINOR]"

  patch:
    description: "Commit message prefixes to trigger an update of the patch version number"
    required: false
    default: "[PATCH]"

  token:
    description: "Repo PAT or GITHUB_TOKEN"
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}

outputs:
  old-version:
    description: "Old version code"
  new-version:
    description: "New version code"

runs:
  using: "node12"
  main: "dist/index.js"
