name: "auto-version"
description: "Update package.json version"

inputs:
  major:
    description: "Commit message prefixes to trigger an update of the major version number"
    required: false
    default: "[MAJOR]"

  minor:
    description: "Commit message prefixes to trigger an update of the minor version number"
    required: false
    default: "[MINOR]"

  patch:
    description: "Commit message prefixes to trigger an update of the patch version number"
    required: false
    default: "[PATCH]"

  token:
    description: "Repo PAT or GITHUB_TOKEN"
    required: true

  message:
    description: "Template for commit messages. Use '%s' for the new version, e.g. 'Updated to version %s'."
    required: false
    default: "Updated to version %s"

  no-prefix:
    description: >
      Defaults to 'error'. Specifies the exit code to use if no prefix is found in any of the commits that are pushed. 
      Valid values are 'success' and 'error' for an exit code of 0 or 1 respectively.
    required: false
    default: "error"

outputs:
  old-version:
    description: "Old version code"
  new-version:
    description: "New version code"

runs:
  using: "node12"
  main: "dist/index.js"
