name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "release/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: auto-version
        id: auto-version
        uses: ./
        with:
          token: ${{ github.token }}
        continue-on-error: true

      - if: steps.auto-version.outcome == 'failure'
        run: echo "${{toJSON(steps.auto-version)}}"

  test-no-prefix: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: auto-version
        id: auto-version
        uses: ./
        with:
          major: |
            BREAKING CHANGE
          minor: |
            feat
          patch: |
            fix
          token: ${{ github.token }}
          no-prefix: "success"

      - name: Check commits
        run: git log --pretty=format:%s -n 1
