name: "test-build"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "release/*"

jobs:
  # Make sure build/ci work properly
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all