name: "test-action"
on:
  push:
    branches:
      - main
      - "release/*"

jobs:
  # Make sure the action works on a clean machine without building
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: auto-version
        id: auto-version
        uses: ./
        with:
          token: ${{ github.token }}
        continue-on-error: true

      - if: steps.auto-version.outcome == 'failure'
        run: echo "${{toJSON(steps.auto-version)}}"

  test-no-prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: auto-version
        id: auto-version
        uses: ./
        with:
          major: |
            BREAKING CHANGE
          minor: |
            feat
          patch: |
            fix
            docs
            chore
          token: ${{ github.token }}
          no-prefix: "success"

      - run: git log --pretty=format:%s -n 1

      - run: git push
